### ISSUE TITLE
crash lol

### ISSUE THREAD

**Issue by blakerview** [KebsCS/League-Instant-Gifting#1]
lol crash when i try to open client while debug is on enable

**Comment by KebsCS** [comment]
Could you explain further what's happening? Also make sure you open the program after league has fully loaded, like on the showcase video

**Comment by blakerview** [comment]
I tried to follow your video but if i try to open League when your program running with enabled debugging League crash, if i try to open League while your program Is running on nothing say to restart lol with debugging on enabled, but if i try this League crash. Down here i leave my discord Nick add me only one sec pls. I Need this program. 
blaker#9809

**Comment by KebsCS** [comment]
1. Enable debugging and close the program
2. Login to league and wait until it fully loads
3. Open the program again

**Comment by blakerview** [comment]
not this the problem but now is ok ty anyway
